apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexodus
spec:
  destination:
    name: in-cluster
    namespace: nexodus
  source:
    path: deploy/nexodus/overlays/prod
    repoURL: 'https://github.com/nexodus-io/nexodus'
    targetRevision: prod
  project: nexodus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
